### ISSUE TITLE
4 column need spacing between each item

### ISSUE THREAD

**Issue by greatbek** [SoftwareStudio/TALearningSite#15]

**Comment by farrukhsubhani** [comment]
You need to do following on http://bek.azurewebsites.net/bek.html
1. Add a div in each column
2. Put all items inside each div and give it appropriate gap using classes

**Comment by greatbek** [comment]
I need to 
- create a parent div
- change its background to colum background
- remove background colour from columns

**Comment by greatbek** [comment]
all done. just waiting for the sync now.
